name: Test Project
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get code 
        uses: actions/checkout@v4.1.2
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
